DELETE FROM birds;
DELETE FROM families;
DELETE FROM regions;

INSERT INTO regions (id, name) VALUES
(1,'Eastern Macedonia & Thrace'),
(2,'Attica'),
(3,'North Aegean'),
(4,'Western Greece'),
(5,'Western Macedonia'),
(6,'Epirus'),
(7,'Thessaly'),
(8,'Ionian Islands'),
(9,'Central Macedonia'),
(10,'Crete'),
(11,'South Aegean'),
(12,'Peloponnese'),
(13,'Central Greece');
ALTER TABLE regions AUTO_INCREMENT = 14;

INSERT INTO families (id, name) VALUES
(1, 'Phasianidae'),
(2, 'Anatidae'),
(3, 'Podicipedidae'),
(4, 'Phoenicopteridae'),
(5, 'Columbidae'),
(6, 'Pteroclidae'),
(7, 'Caprimulgidae'),
(8, 'Apodidae'),
(9, 'Cuculidae'),
(10, 'Rallidae'),
(11, 'Gruidae'),
(12, 'Otididae'),
(13, 'Gaviidae'),
(14, 'Hydrobatidae'),
(15, 'Procellariidae'),
(16, 'Ciconiidae'),
(17, 'Threskiornithidae'),
(18, 'Ardeidae'),
(19, 'Pelecanidae'),
(20, 'Sulidae'),
(21, 'Phalacrocoracidae'),
(22, 'Burhinidae'),
(23, 'Haematopodidae'),
(24, 'Recurvirostridae'),
(25, 'Charadriidae'),
(26, 'Scolopacidae'),
(27, 'Glareolidae'),
(28, 'Laridae'),
(29, 'Stercorariidae'),
(30, 'Tytonidae'),
(31, 'Strigidae'),
(32, 'Pandionidae'),
(33, 'Accipitridae'),
(34, 'Upupidae'),
(35, 'Meropidae'),
(36, 'Coraciidae'),
(37, 'Alcedinidae'),
(38, 'Picidae'),
(39, 'Falconidae'),
(40, 'Psittacidae'),
(41, 'Oriolidae'),
(42, 'Laniidae'),
(43, 'Corvidae'),
(44, 'Paridae'),
(45, 'Remizidae'),
(46, 'Alaudidae'),
(47, 'Panuridae'),
(48, 'Cisticolidae'),
(49, 'Acrocephalidae'),
(50, 'Locustellidae'),
(51, 'Hirundinidae'),
(52, 'Phylloscopidae'),
(53, 'Scotocercidae'),
(54, 'Aegithalidae'),
(55, 'Sylviidae'),
(56, 'Certhiidae'),
(57, 'Sittidae'),
(58, 'Troglodytidae'),
(59, 'Cinclidae'),
(60, 'Sturnidae'),
(61, 'Turdidae'),
(62, 'Muscicapidae'),
(63, 'Regulidae'),
(64, 'Bombycillidae'),
(65, 'Prunellidae'),
(66, 'Passeridae'),
(67, 'Motacillidae'),
(68, 'Fringillidae'),
(69, 'Calcariidae'),
(70, 'Emberizidae');
ALTER TABLE families AUTO_INCREMENT = 71;

INSERT INTO birds (id, name, scientific_name, family_id, image_url) VALUES
(1,'Common Quail','Coturnix coturnix',1,'https://upload.wikimedia.org/wikipedia/commons/e/e2/A_common_quail_in_Lebanon%2C_crop.jpg'),
(2,'Rock Partridge','Alectoris graeca',1,'https://upload.wikimedia.org/wikipedia/commons/c/c9/Steinhuhn.jpg'),
(3,'Chukar','Alectoris chukar',1,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Alectoris_chukar_%28AM_LB4107-2%29.jpg'),
(4,'Red-legged Partridge','Alectoris rufa',1,'https://upload.wikimedia.org/wikipedia/commons/f/f3/Alectoris_rufa_-Kirkmichael%2C_Scotland-8.jpg'),
(5,'Black Francolin','Francolinus francolinus',1,'https://upload.wikimedia.org/wikipedia/commons/9/9d/Black_Francolin.jpg'),
(6,'Common Pheasant','Phasianus colchicus',1,'https://upload.wikimedia.org/wikipedia/commons/a/aa/Pheasant_%28Phasianus_colchicus%29_%E2%99%82_%2851028701818%29.jpg'),
(7,'Grey Partridge','Perdix perdix',1,'https://upload.wikimedia.org/wikipedia/commons/3/31/Perdix_perdix_Turvey_3.jpg'),
(8,'Hazel Grouse','Tetrastes bonasia',1,'https://upload.wikimedia.org/wikipedia/commons/e/e8/Bonasa_bonasia.JPG'),
(9,'Western Capercaillie','Tetrao urogallus',1,'https://upload.wikimedia.org/wikipedia/commons/f/ff/Capercaillie%281%29.jpg'),
(10,'Black Grouse','Tetrao tetrix',1,'https://upload.wikimedia.org/wikipedia/commons/8/8e/Birkhahn.jpg'),
(11,'White-headed Duck','Oxyura leucocephala',2,'https://upload.wikimedia.org/wikipedia/commons/d/d7/Female_white_headed_duck.JPG'),
(12,'Mute Swan','Cygnus olor',2,'https://upload.wikimedia.org/wikipedia/commons/9/9a/20090512_Trezzo_7667_1024x768.jpg'),
(13,'Whooper Swan','Cygnus cygnus',2,'https://upload.wikimedia.org/wikipedia/commons/d/da/Bewick%27s_Swans_at_Big_Waters.jpg'),
(14,'Tundra Swan','Cygnus columbianus',2,'https://upload.wikimedia.org/wikipedia/commons/4/4a/Cygnus_bewickii_01.jpg'),
(15,'Brent Goose','Branta bernicla',2,'https://upload.wikimedia.org/wikipedia/commons/2/26/Atlantic_Brant_Fly-By_Wiki.png'),
(16,'Red-breasted Goose','Branta ruficollis',2,'https://upload.wikimedia.org/wikipedia/commons/8/8f/Branta_ruficollis.jpg'),
(17,'Snow Goose','Anser caerulescens',2,'https://upload.wikimedia.org/wikipedia/commons/e/e2/Anser_caerulescens_CT8.jpg'),
(18,'Greylag Goose','Anser anser',2,'https://upload.wikimedia.org/wikipedia/commons/d/db/101777%E5%8F%B0%E5%8D%97%E7%99%BC%E7%8F%BE%E8%B1%86%E9%9B%81.jpg'),
(19,'Bean Goose','Anser fabalis',2,'https://upload.wikimedia.org/wikipedia/commons/0/07/Anser_fabalis_fabalis%2C_Kurortny_District%2C_St_Petersburg%2C_Russia_1.jpg'),
(20,'Greater White-fronted Goose','Anser albifrons',2,'https://upload.wikimedia.org/wikipedia/commons/0/0f/Greater_white-fronted_goose_in_flight-1045.jpg'),
(21,'Lesser White-fronted Goose','Anser erythropus',2,'https://upload.wikimedia.org/wikipedia/commons/9/97/Anser_erythropus.jpg'),
(22,'Long-tailed Duck','Clangula hyemalis',2,'https://upload.wikimedia.org/wikipedia/commons/8/8e/Long-tailed-duck.jpg'),
(23,'Common Eider','Somateria mollissima',2,'https://upload.wikimedia.org/wikipedia/commons/0/07/Flickr_-_Rainbirder_-_Eider_drake_%28Somateria_mollissima%29_in_flight.jpg'),
(24,'Velvet Scoter','Melanitta fusca',2,'https://upload.wikimedia.org/wikipedia/commons/3/35/Velvet_Scoter%2C_Eyebrook_Reservoir%2C_Leics.jpg'),
(25,'Common Scoter','Melanitta nigra',2,'https://upload.wikimedia.org/wikipedia/commons/9/98/Eurasian_common_scoter.jpg'),
(26,'Common Goldeneye','Bucephala clangula',2,'https://upload.wikimedia.org/wikipedia/commons/1/1e/Bucephala_clangula_18042024_Kaijonlahti%2C_Finland_02.jpg'),
(27,'Smew','Mergellus albellus',2,'https://upload.wikimedia.org/wikipedia/commons/0/06/Smew_RWD1.jpg'),
(28,'Goosander','Mergus merganser',2,'https://upload.wikimedia.org/wikipedia/commons/7/7c/062_-_COMMON_MERGANSER_%281-5-13%29_patagonia_lake%2C_scc%2C_az_%281%29_%288717954203%29.jpg'),
(29,'Red-breasted Merganser','Mergus serrator',2,'https://upload.wikimedia.org/wikipedia/commons/7/77/Hwyaden_Frongoch_3.jpg'),
(30,'Common Shelduck','Tadorna tadorna',2,'https://upload.wikimedia.org/wikipedia/commons/3/3f/500px_photo_%2831688843%29.jpeg'),
(31,'Ruddy Shelduck','Tadorna ferruginea',2,'https://upload.wikimedia.org/wikipedia/commons/d/d0/A_couple_of_Tadorna_ferruginea.jpg'),
(32,'Marbled Teal','Marmaronetta angustirostris',2,'https://upload.wikimedia.org/wikipedia/commons/d/d4/Marmaronetta_angustirostris%2C_London_Wetland_Centre%2C_UK_-_Diliff.jpg'),
(33,'Red-crested Pochard','Netta rufina',2,'https://upload.wikimedia.org/wikipedia/commons/5/50/Netta_rufina_%28Red-crested_Pochard%29_Male%2C_London_Wetland_Centre_-_Diliff.jpg'),
(34,'Common Pochard','Aythya ferina',2,'https://upload.wikimedia.org/wikipedia/commons/5/5c/Aythya_ferina_Sandwell_2.jpg'),
(35,'Ferruginous Duck','Aythya nyroca',2,'https://upload.wikimedia.org/wikipedia/commons/a/a2/Aythya_nyroca_at_Martin_Mere_1.jpg'),
(36,'Tufted Duck','Aythya fuligula',2,'https://upload.wikimedia.org/wikipedia/commons/7/73/Tufted_Duck_09_05_2025_02.jpg'),
(37,'Greater Scaup','Aythya marila',2,'https://upload.wikimedia.org/wikipedia/commons/b/b9/Drake_Greater_scaup_%28Aythya_marila%29_Barnegat_Inlet%2C_New_Jersey%2C_USA.jpg'),
(38,'Garganey','Anas querquedula',2,'https://upload.wikimedia.org/wikipedia/commons/6/60/Anas_querquedula%2C_Slottsskogen%2C_G%C3%B6teborg%2C_Sweden_1.jpg'),
(39,'Northern Shoveler','Anas clypeata',2,'https://upload.wikimedia.org/wikipedia/commons/7/70/Northern_shoveler_pair_in_Marine_Park_%2833233%29.jpg'),
(40,'Blue-winged Teal','Anas discors',2,'https://upload.wikimedia.org/wikipedia/commons/c/cd/Blue-winged_teal_at_Sacramento_National_Wildlife_Refuge-5326.jpg'),
(41,'Gadwall','Anas strepera',2,'https://upload.wikimedia.org/wikipedia/commons/2/2e/Gadwall-female.jpg'),
(42,'Eurasian Wigeon','Anas penelope',2,'https://upload.wikimedia.org/wikipedia/commons/6/64/1J6A3215-Eurasian_Wigeon.jpg'),
(43,'Mallard','Anas platyrhynchos',2,'https://upload.wikimedia.org/wikipedia/commons/a/ab/20250709_mallard_duckling_wethersfield_cove_PD208385_1.jpg'),
(44,'Northern Pintail','Anas acuta',2,'https://upload.wikimedia.org/wikipedia/commons/0/0b/Northern_Pintails_%28Male_%26_Female%29_I_IMG_0911.jpg'),
(45,'Common Teal','Anas crecca',2,'https://upload.wikimedia.org/wikipedia/commons/a/a4/Anas_carolinensis_%28Green-winged_Teal%29_male.jpg'),
(46,'Little Grebe','Tachybaptus ruficollis',3,'https://upload.wikimedia.org/wikipedia/commons/8/84/Little_grebe_Zwergtaucher.jpg'),
(47,'Red-necked Grebe','Podiceps grisegena',3,'https://upload.wikimedia.org/wikipedia/commons/5/59/Podiceps_grisegena_%2833624738966%29.jpg'),
(48,'Great Crested Grebe','Podiceps cristatus',3,'https://upload.wikimedia.org/wikipedia/commons/b/ba/Great_Crested_Grebe_%28Podiceps_cristatus%29_%2826662808186%29.jpg'),
(49,'Horned Grebe','Podiceps auritus',3,'https://upload.wikimedia.org/wikipedia/commons/7/77/Podiceps_auritus_%2813909539717%29.jpg'),
(50,'Black-necked Grebe','Podiceps nigricollis',3,'https://upload.wikimedia.org/wikipedia/commons/1/1b/099_-_EARED_GREBE_%2811-27-07%29_oso_flaco%2C_sloco%2C_ca_%281%29_%288721001643%29.jpg'),
(51,'Greater Flamingo','Phoenicopterus roseus',4,'https://upload.wikimedia.org/wikipedia/commons/8/81/010_Greater_flamingos_male_and_female_in_the_Camargue_during_mating_season_Photo_by_Giles_Laurent.jpg'),
(52,'Rock Dove','Columba livia',5,'https://upload.wikimedia.org/wikipedia/commons/1/13/Columba_livia_-_01.jpg'),
(53,'Stock Dove','Columba oenas',5,'https://upload.wikimedia.org/wikipedia/commons/6/69/2018-03-22_Columba_oenas%2C_Jesmond_Dene_4.jpg'),
(54,'Common Woodpigeon','Columba palumbus',5,'https://upload.wikimedia.org/wikipedia/commons/0/05/Columba_palumbus_eating.JPG'),
(55,'European Turtle-dove','Streptopelia turtur',5,'https://upload.wikimedia.org/wikipedia/commons/8/87/2006_1031turturduva0224.JPG'),
(56,'Oriental Turtle-dove','Streptopelia orientalis',5,'https://upload.wikimedia.org/wikipedia/commons/9/9f/Av_Oriental_Turtle-Dove_JG.jpg'),
(57,'Eurasian Collared-dove','Streptopelia decaocto',5,'https://upload.wikimedia.org/wikipedia/commons/f/fa/2022-04-06_Streptopelia_decaocto%2C_Plovdiv%2C_Bulgaria_1.jpg'),
(58,'Laughing Dove','Streptopelia senegalensis',5,'https://upload.wikimedia.org/wikipedia/commons/3/3e/Dove_Iran.jpg'),
(59,'Pallas''s Sandgrouse','Syrrhaptes paradoxus',6,'https://upload.wikimedia.org/wikipedia/commons/9/98/Syrrhapte_paradoxal.jpg'),
(60,'Black-bellied Sandgrouse','Pterocles orientalis',6,'https://upload.wikimedia.org/wikipedia/commons/2/21/Pterocles_orientalis_in_flight.jpg'),
(61,'Pin-tailed Sandgrouse','Pterocles alchata',6,'https://upload.wikimedia.org/wikipedia/commons/8/8c/Pin-tailed_sandgrouse_%28Pterocles_alchata%29.jpg'),
(62,'European Nightjar','Caprimulgus europaeus',7,'https://upload.wikimedia.org/wikipedia/commons/a/ae/Adultwithchicks.jpg'),
(63,'Alpine Swift','Apus melba',8,'https://upload.wikimedia.org/wikipedia/commons/4/4d/%CE%92%CE%BF%CF%85%CE%BD%CE%BF%CF%83%CF%84%CE%B1%CF%87%CF%84%CE%AC%CF%81%CE%B1_Alpine_Swift_Tachymarptis_melba.jpg'),
(64,'Little Swift','Apus affinis',8,'https://upload.wikimedia.org/wikipedia/commons/f/f7/Little_swift%2C_Apus_affinis%2C_at_Kruger_National_Park%2C_South_Africa%2C_crop.jpg'),
(65,'Pallid Swift','Apus pallidus',8,'https://upload.wikimedia.org/wikipedia/commons/d/db/Pallid_Swift_by_Irvin_Calicut_IRV07813.jpg'),
(66,'Common Swift','Apus apus',8,'https://upload.wikimedia.org/wikipedia/commons/b/be/Apus_apus_-Barcelona%2C_Spain-8_%281%29.jpg'),
(67,'Great Spotted Cuckoo','Clamator glandarius',9,'https://upload.wikimedia.org/wikipedia/commons/9/91/Clamator_glandarius_%28cropped_2%29.jpg'),
(68,'Common Cuckoo','Cuculus canorus',9,'https://upload.wikimedia.org/wikipedia/commons/4/4f/Kuckuck_%28Cuculus_canorus%29_by_Tim_Peukert.jpg'),
(69,'Western Water Rail','Rallus aquaticus',10,'https://upload.wikimedia.org/wikipedia/commons/b/b3/Water_rail_2022_04_30_01.jpg'),
(70,'Corncrake','Crex crex',10,'https://upload.wikimedia.org/wikipedia/commons/7/76/Ruisr%C3%A4%C3%A4kk%C3%A4.JPG'),
(71,'Spotted Crake','Porzana porzana',10,'https://upload.wikimedia.org/wikipedia/commons/4/42/Porzana_porzana_6_%28Marek_Szczepanek%29.jpg'),
(72,'Little Crake','Porzana parva',10,'https://upload.wikimedia.org/wikipedia/commons/8/81/Porzana_parva_%2850%29.jpg'),
(73,'Baillon''s Crake','Porzana pusilla',10,'https://upload.wikimedia.org/wikipedia/commons/6/6d/Baillon%27s_Crake.jpg'),
(74,'Purple Swamphen','Porphyrio porphyrio',10,'https://upload.wikimedia.org/wikipedia/commons/6/61/Porphyrio_porphyrio%2C_P%C3%AAra%2C_Algarve%2C_Portugal_2.jpg'),
(75,'Allen''s Gallinule','Porphyrio alleni',10,'https://upload.wikimedia.org/wikipedia/commons/4/45/Allen%27s_gallinule%2C_Porphyrio_alleni%2C_at_Chobe_National_Park%2C_Botswana.jpg'),
(76,'Common Moorhen','Gallinula chloropus',10,'https://upload.wikimedia.org/wikipedia/commons/7/7a/Austin_Roberts_Bird_Sanctuary-032.jpg'),
(77,'Common Coot','Fulica atra',10,'https://upload.wikimedia.org/wikipedia/commons/7/77/2_Kilogramm_wird_ein_gut_gen%C3%A4hrter_Graureiher_schwer._08.jpg'),
(78,'Demoiselle Crane','Grus virgo',11,'https://upload.wikimedia.org/wikipedia/commons/c/c3/Demoiselle_Cranes_at_Tal_Chappar.jpg'),
(79,'Common Crane','Grus grus',11,'https://upload.wikimedia.org/wikipedia/commons/2/23/Grus_grus_2_%28Marek_Szczepanek%29.jpg'),
(80,'Little Bustard','Tetrax tetrax',12,'https://upload.wikimedia.org/wikipedia/commons/1/10/British_birds_in_their_haunts_%28Cuculus_canorus%29.jpg'),
(81,'Great Bustard','Otis tarda',12,'https://upload.wikimedia.org/wikipedia/commons/9/90/Drop_f%C3%BAzat%C3%BD_%28Otis_tarda%29_%282416576086%29.jpg'),
(82,'African Houbara','Chlamydotis undulata',12,'https://upload.wikimedia.org/wikipedia/commons/4/45/Houbara035.JPG'),
(83,'Red-throated Loon','Gavia stellata',13,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Gavia_Stellata_%C3%96lfus%C3%A1_20090606.jpg'),
(84,'Arctic Loon','Gavia arctica',13,'https://upload.wikimedia.org/wikipedia/commons/3/3e/Black-throated_Diver%2C_Oulu%2C_Finland_02_%2815195370798%29.jpg'),
(85,'Common Loon','Gavia immer',13,'https://upload.wikimedia.org/wikipedia/commons/1/15/093_-_COMMON_LOON_%2812-17-11%29_moss_landing%2C_ca_%282%29_%288720312789%29.jpg'),
(86,'European Storm-petrel','Hydrobates pelagicus',14,'https://upload.wikimedia.org/wikipedia/commons/b/b4/European_storm_petrel_%28Hydrobates_pelagicus%29_Sagres.jpg'),
(87,'Scopoli''s Shearwater','Calonectris diomedea',15,'https://upload.wikimedia.org/wikipedia/commons/d/da/Gelbschnabel-Sturmtaucher_DSC_0111-Padela.jpg'),
(88,'Great Shearwater','Puffinus gravis',15,'https://upload.wikimedia.org/wikipedia/commons/4/48/Greater_shearwater_%28Ardenna_gravis%29_Sagres.jpg'),
(89,'Sooty Shearwater','Puffinus griseus',15,'https://upload.wikimedia.org/wikipedia/commons/7/7c/Ardenna_grisea%2C_North_Sea_10_km_off_Northumberland_coast_5.jpg'),
(90,'Yelkouan Shearwater','Puffinus yelkouan',15,'https://upload.wikimedia.org/wikipedia/commons/6/68/Puffinus_yelkouan_140249998.jpg'),
(91,'Balearic Shearwater','Puffinus mauretanicus',15,'https://upload.wikimedia.org/wikipedia/commons/6/62/Puffinus_mauretanicus.jpg'),
(92,'Black Stork','Ciconia nigra',16,'https://upload.wikimedia.org/wikipedia/commons/e/e2/Black_Stork_Manas_Assam_India_December_2018.jpg'),
(93,'White Stork','Ciconia ciconia',16,'https://upload.wikimedia.org/wikipedia/commons/8/81/2017-03-11_Migratory_storks_resting_in_Rahat.jpg'),
(94,'Eurasian Spoonbill','Platalea leucorodia',17,'https://upload.wikimedia.org/wikipedia/commons/8/8c/Eurasian_Spoonbill-2.jpg'),
(95,'Glossy Ibis','Plegadis falcinellus',17,'https://upload.wikimedia.org/wikipedia/commons/0/0f/023_Glossy_ibis_fishing_in_the_Camargue_Photo_by_Giles_Laurent.jpg'),
(96,'Eurasian Bittern','Botaurus stellaris',18,'https://upload.wikimedia.org/wikipedia/commons/3/3b/Botaurus_stellaris_-Minsmere_RSPB_reserve%2C_Suffolk%2C_England-8.jpg'),
(97,'Common Little Bittern','Ixobrychus minutus',18,'https://upload.wikimedia.org/wikipedia/commons/f/fc/Ixobrychus_minutus_2_%28Marek_Szczepanek%29.jpg'),
(98,'Black-crowned Night-heron','Nycticorax nycticorax',18,'https://upload.wikimedia.org/wikipedia/commons/b/bf/A_Night_Heron_building_a_nest.JPG'),
(99,'Striated Heron','Butorides striata',18,'https://upload.wikimedia.org/wikipedia/commons/4/47/Butorides_striata_striata%2C_Rio_de_Janeiro%2C_Brazil_423402865.jpg'),
(100,'Squacco Heron','Ardeola ralloides',18,'https://upload.wikimedia.org/wikipedia/commons/6/6e/Crabier_chevelu.jpg'),
(101,'Cattle Egret','Bubulcus ibis',18,'https://upload.wikimedia.org/wikipedia/commons/8/8c/Bubulcus_ibis_-Dallas%2C_Texas%2C_USA_-flying-8.jpg'),
(102,'Grey Heron','Ardea cinerea',18,'https://upload.wikimedia.org/wikipedia/commons/0/09/Graureiher_Grey_Heron.jpg'),
(103,'Purple Heron','Ardea purpurea',18,'https://upload.wikimedia.org/wikipedia/commons/5/5b/Purple_heron_-_Vadodara_2022-01-08.jpg'),
(104,'Great White Egret','Egretta alba',18,'https://upload.wikimedia.org/wikipedia/commons/7/76/Ardea_alba_-San_Francisco_Bay%2C_California%2C_USA_-flying-8-1c.jpg'),
(105,'Black Heron','Egretta ardesiaca',18,'https://upload.wikimedia.org/wikipedia/commons/a/a0/Balck_Heron_canopy_crop.jpg'),
(106,'Little Egret','Egretta garzetta',18,'https://upload.wikimedia.org/wikipedia/commons/f/fe/Seidenreiher_Little_egret.jpg'),
(107,'Western Reef-egret','Egretta gularis',18,'https://upload.wikimedia.org/wikipedia/commons/4/4a/Egretta_gularis_-Egypt-8.jpg'),
(108,'Dalmatian Pelican','Pelecanus crispus',19,'https://upload.wikimedia.org/wikipedia/commons/a/a5/Argyropelekanos.jpg'),
(109,'Great White Pelican','Pelecanus onocrotalus',19,'https://upload.wikimedia.org/wikipedia/commons/c/c8/Danube_Delta_pelican_flying.jpg'),
(110,'Northern Gannet','Morus bassanus',20,'https://upload.wikimedia.org/wikipedia/commons/2/2d/Morus_bassanus_adu.jpg'),
(111,'Pygmy Cormorant','Phalacrocorax pygmeus',21,'https://upload.wikimedia.org/wikipedia/commons/5/5e/PygmyCormorantKinneret.jpg'),
(112,'European Shag','Phalacrocorax aristotelis',21,'https://upload.wikimedia.org/wikipedia/commons/9/9f/Composite_image_of_Gulosus_aristotelis_jumping_into_the_sea_%28Croatia%29.jpg'),
(113,'Great Cormorant','Phalacrocorax carbo',21,'https://upload.wikimedia.org/wikipedia/commons/c/c3/2021-05-05_Phalacrocorax_carbo_carbo%2C_Killingworth_Lake%2C_Northumberland_1-1.jpg'),
(114,'Eurasian Thick-knee','Burhinus oedicnemus',22,'https://upload.wikimedia.org/wikipedia/commons/d/d8/Burhinus_oedicnemus_insularum_Lanzarote_1.jpg'),
(115,'Eurasian Oystercatcher','Haematopus ostralegus',23,'https://upload.wikimedia.org/wikipedia/commons/1/11/Austernfischer_Haematopus_ostralegus_Iceland_RB_zugeschnitten.jpg'),
(116,'Pied Avocet','Recurvirostra avosetta',24,'https://upload.wikimedia.org/wikipedia/commons/2/22/Avocet_from_the_Crossley_ID_Guide_Britain_and_Ireland.jpg'),
(117,'Black-winged Stilt','Himantopus himantopus',24,'https://upload.wikimedia.org/wikipedia/commons/b/be/Black-winged_Stilt%2C_Common_Stilt%2C_or_Pied_Stilt%2C_Himantopus_himantopus_at_Marievale_Nature_Reserve%2C_Gauteng%2C_South_Africa._%2844754808815%29.jpg'),
(118,'Grey Plover','Pluvialis squatarola',25,'https://upload.wikimedia.org/wikipedia/commons/1/16/Breeding_plumage_Black-bellied_plover_%28Pluvialis_squatarola%29_Great_Bay_Wildlife_Management_Area%2C_New_Jersey%2C_USA.png'),
(119,'Eurasian Golden Plover','Pluvialis apricaria',25,'https://upload.wikimedia.org/wikipedia/commons/a/a9/Chorlitejos_dorados_en_vuelo_-_Eurasian_golden_plover_-_Pluvialis_apricaria.jpg'),
(120,'Pacific Golden Plover','Pluvialis fulva',25,'https://upload.wikimedia.org/wikipedia/commons/e/ec/Pluvialis_fulva_2_-_Laem_Pak_Bia.jpg'),
(121,'Eurasian Dotterel','Charadrius morinellus',25,'https://upload.wikimedia.org/wikipedia/commons/b/bb/Charadrius_morinellus_male.jpg'),
(122,'Common Ringed Plover','Charadrius hiaticula',25,'https://upload.wikimedia.org/wikipedia/commons/d/d2/Common_ringed_plover_%28Charadrius_hiaticula%29_Oppdal.jpg'),
(123,'Little Ringed Plover','Charadrius dubius',25,'https://upload.wikimedia.org/wikipedia/commons/e/ed/Xilx%C3%AElok.jpg'),
(124,'Kittlitz''s Plover','Charadrius pecuarius',25,'https://upload.wikimedia.org/wikipedia/commons/7/79/Kittlitz%27s_plover_%28Charadrius_pecuarius%29.jpg'),
(125,'Kentish Plover','Charadrius alexandrinus',25,'https://upload.wikimedia.org/wikipedia/commons/6/6f/Kentish_Plover_Charadrius_alexandrinus%2C_India.jpg'),
(126,'Greater Sandplover','Charadrius leschenaultii',25,'https://upload.wikimedia.org/wikipedia/commons/3/3a/2024-07-26_Anarhynchus_leschenaultii_leschenaultii%2C_Newbiggin%2C_Northumberland_1.jpg'),
(127,'Caspian Plover','Charadrius asiaticus',25,'https://upload.wikimedia.org/wikipedia/commons/b/ba/Caspian_plover_%28Charadrius_asiaticus%29_image.jpg'),
(128,'Northern Lapwing','Vanellus vanellus',25,'https://upload.wikimedia.org/wikipedia/commons/c/c4/Birds_of_Sweden_2016_45.jpg'),
(129,'Spur-winged Lapwing','Vanellus spinosus',25,'https://upload.wikimedia.org/wikipedia/commons/4/4b/Spur-wingedPlover-withChick.jpg'),
(130,'Sociable Lapwing','Vanellus gregarius',25,'https://upload.wikimedia.org/wikipedia/commons/6/62/SociablePlover.jpg'),
(131,'White-tailed Lapwing','Vanellus leucurus',25,'https://upload.wikimedia.org/wikipedia/commons/8/86/White-tailed_lapwing_%28Vanellus_leucurus%29.jpg'),
(132,'Upland Sandpiper','Bartramia longicauda',26,'https://upload.wikimedia.org/wikipedia/commons/c/cf/UplandSandpiperOntarioCropped.jpg'),
(133,'Whimbrel','Numenius phaeopus',26,'https://upload.wikimedia.org/wikipedia/commons/0/0c/Whimbrel_Numenius_phaeopus.jpg'),
(134,'Slender-billed Curlew','Numenius tenuirostris',26,'https://upload.wikimedia.org/wikipedia/commons/a/ae/Naturalis_Biodiversity_Center_-_ZMA.AVES.1670_-_Numenius_tenuirostris_Vieillot%2C_1817_-_Scolopacidae_-_skin_specimen_%28cropped%29.jpeg'),
(135,'Eurasian Curlew','Numenius arquata',26,'https://upload.wikimedia.org/wikipedia/commons/6/67/Curlew_%28Numenius_arquata%29_in_flight.jpg'),
(136,'Bar-tailed Godwit','Limosa lapponica',26,'https://upload.wikimedia.org/wikipedia/commons/c/ca/Bar-tailed_Godwit.jpg'),
(137,'Black-tailed Godwit','Limosa limosa',26,'https://upload.wikimedia.org/wikipedia/commons/0/03/Black-tailed_godwit_%28Limosa_limosa%29_in_flight_2.jpg'),
(138,'Ruddy Turnstone','Arenaria interpres',26,'https://upload.wikimedia.org/wikipedia/commons/c/cc/Arenaria_interpres4.jpg'),
(139,'Red Knot','Calidris canutus',26,'https://upload.wikimedia.org/wikipedia/commons/3/3f/Calidris_canutus_%28summer%29.jpg'),
(140,'Ruff','Calidris pugnax',26,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Philomachus_pugnax_-Diergaarde_Blijdorp-8c.jpg'),
(141,'Broad-billed Sandpiper','Calidris falcinellus',26,'https://upload.wikimedia.org/wikipedia/commons/f/fb/Broad_billed_sandpiper_by_Sreedev_Puthur.jpg'),
(142,'Stilt Sandpiper','Calidris himantopus',26,'https://upload.wikimedia.org/wikipedia/commons/7/75/Calidris_himantopus.jpg'),
(143,'Curlew Sandpiper','Calidris ferruginea',26,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Calidris_ferruginea_%28Marek_Szczepanek%29.jpg'),
(144,'Temminck''s Stint','Calidris temminckii',26,'https://upload.wikimedia.org/wikipedia/commons/6/6b/Temmincks_Stint.jpg'),
(145,'Sanderling','Calidris alba',26,'https://upload.wikimedia.org/wikipedia/commons/2/27/Calidris-alba-001.jpg'),
(146,'Dunlin','Calidris alpina',26,'https://upload.wikimedia.org/wikipedia/commons/e/e1/Alpenstrandl%C3%A4ufer_%28calidris_alpina%29_-_Spiekeroog%2C_Nationalpark_nieders%C3%A4chsisches_Wattenmeer.jpg'),
(147,'Purple Sandpiper','Calidris maritima',26,'https://upload.wikimedia.org/wikipedia/commons/a/ad/2019-08-13_02_Purple_Sandpiper_%28Calidris_maritima%29%2C_Reykjavik_Iceland.jpg'),
(148,'Baird''s Sandpiper','Calidris bairdii',26,'https://upload.wikimedia.org/wikipedia/commons/0/08/Calidris_bairdii.jpg'),
(149,'Little Stint','Calidris minuta',26,'https://upload.wikimedia.org/wikipedia/commons/7/77/Little_Stint_%28Calidris_minuta%29_2.jpg'),
(150,'White-rumped Sandpiper','Calidris fuscicollis',26,'https://upload.wikimedia.org/wikipedia/commons/7/7b/Calidris_fuscicollis_PLAYERO_RABADILLA_BLANCA.jpg'),
(151,'Buff-breasted Sandpiper','Calidris subruficollis',26,'https://upload.wikimedia.org/wikipedia/commons/f/fc/Grasl%C3%A4ufer.jpg'),
(152,'Pectoral Sandpiper','Calidris melanotos',26,'https://upload.wikimedia.org/wikipedia/commons/1/17/Pectoral-Sandpiper017.jpg'),
(153,'Long-billed Dowitcher','Limnodromus scolopaceus',26,'https://upload.wikimedia.org/wikipedia/commons/8/85/Limnodromus_scolopaceus.jpg'),
(154,'Eurasian Woodcock','Scolopax rusticola',26,'https://upload.wikimedia.org/wikipedia/commons/1/1c/Woodcock_earthworm.jpg'),
(155,'Great Snipe','Gallinago media',26,'https://upload.wikimedia.org/wikipedia/commons/5/5a/Greatsnipe_1000.jpg'),
(156,'Common Snipe','Gallinago gallinago',26,'https://upload.wikimedia.org/wikipedia/commons/c/cc/CommonSnipe.jpg'),
(157,'Jack Snipe','Lymnocryptes minimus',26,'https://upload.wikimedia.org/wikipedia/commons/c/c9/Jack_snipe.png'),
(158,'Wilson''s Phalarope','Phalaropus tricolor',26,'https://upload.wikimedia.org/wikipedia/commons/f/f1/Wilson%27s_Phalarope%2C_Oregon_03_%28cropped%29.jpg'),
(159,'Red-necked Phalarope','Phalaropus lobatus',26,'https://upload.wikimedia.org/wikipedia/commons/5/5c/Red-necked_Phalarope.jpg'),
(160,'Red Phalarope','Phalaropus fulicarius',26,'https://upload.wikimedia.org/wikipedia/commons/5/56/Phalaropus_fulicarius_108504718_%28cropped%29.jpg'),
(161,'Terek Sandpiper','Xenus cinereus',26,'https://upload.wikimedia.org/wikipedia/commons/b/ba/Terek_Sandpiper_%28Xenus_cinereus%29_%2853969645800%29.jpg'),
(162,'Common Sandpiper','Actitis hypoleucos',26,'https://upload.wikimedia.org/wikipedia/commons/a/a7/Actitis_hypoleucos_-_Laem_Pak_Bia.jpg'),
(163,'Spotted Sandpiper','Actitis macularius',26,'https://upload.wikimedia.org/wikipedia/commons/e/e7/Actitis-macularia-004.jpg'),
(164,'Green Sandpiper','Tringa ochropus',26,'https://upload.wikimedia.org/wikipedia/commons/4/4a/Green_Sandpiper_%28Tringa_ochropus%29_W_IMG_6454.jpg'),
(165,'Lesser Yellowlegs','Tringa flavipes',26,'https://upload.wikimedia.org/wikipedia/commons/a/a3/Lesser_Yellowlegs.jpg'),
(166,'Spotted Redshank','Tringa erythropus',26,'https://upload.wikimedia.org/wikipedia/commons/d/d3/Spotted_Redshank_Breeding_Plumage.jpg'),
(167,'Common Greenshank','Tringa nebularia',26,'https://upload.wikimedia.org/wikipedia/commons/6/6f/Common_greenshank_%28Tringa_nebularia%29_Bahrain.jpg'),
(168,'Common Redshank','Tringa totanus',26,'https://upload.wikimedia.org/wikipedia/commons/c/c2/Common_Redshank_%283%29.jpg'),
(169,'Wood Sandpiper','Tringa glareola',26,'https://upload.wikimedia.org/wikipedia/commons/f/f0/Bruchwasserl%C3%A4ufer.jpg'),
(170,'Marsh Sandpiper','Tringa stagnatilis',26,'https://upload.wikimedia.org/wikipedia/commons/a/af/Marsh_Sandpiper_in_Chennai.jpg'),
(171,'Cream-coloured Courser','Cursorius cursor',27,'https://upload.wikimedia.org/wikipedia/commons/d/d4/Cream-colored_courser.jpg'),
(172,'Collared Pratincole','Glareola pratincola',27,'https://upload.wikimedia.org/wikipedia/commons/d/d1/Collared_pratincole_%28Glareola_pratincola%29.jpg'),
(173,'Black-winged Pratincole','Glareola nordmanni',27,'https://upload.wikimedia.org/wikipedia/commons/a/a9/Tyrkyshka.jpg'),
(174,'Little Gull','Hydrocoloeus minutus',28,'https://upload.wikimedia.org/wikipedia/commons/a/a2/Bird_Yyterin_lietteet_4.jpg'),
(175,'Black-legged Kittiwake','Rissa tridactyla',28,'https://upload.wikimedia.org/wikipedia/commons/b/bf/Arcticskua.jpg'),
(176,'Slender-billed Gull','Larus genei',28,'https://upload.wikimedia.org/wikipedia/commons/7/7b/Slender-billed_gull_%28Chroicocephalus_genei%29_Bahrain.jpg'),
(177,'Black-headed Gull','Larus ridibundus',28,'https://upload.wikimedia.org/wikipedia/commons/2/29/Chroicocephalus_ridibundus_%28summer%29.jpg'),
(178,'Laughing Gull','Larus atricilla',28,'https://upload.wikimedia.org/wikipedia/commons/1/16/Assateague_laughing_gull_MD1.jpg'),
(179,'Pallas''s Gull','Larus ichthyaetus',28,'https://upload.wikimedia.org/wikipedia/commons/8/8d/Larus_ichthyaetus.jpg'),
(180,'Mediterranean Gull','Larus melanocephalus',28,'https://upload.wikimedia.org/wikipedia/commons/a/a4/Larus_melanocephalus.jpg'),
(181,'White-eyed Gull','Larus leucophthalmus',28,'https://upload.wikimedia.org/wikipedia/commons/6/66/White-eyed_gull_at_the_Red_Sea_2.jpg'),
(182,'Audouin''s Gull','Larus audouinii',28,'https://upload.wikimedia.org/wikipedia/commons/c/cb/Audouin%27s_gull..jpg'),
(183,'Mew Gull','Larus canus',28,'https://upload.wikimedia.org/wikipedia/commons/8/8a/Common_Gull_%28Fiskem%C3%A5ke%29_%28Larus_canus%29_-_Senja%2C_Norway_2023-07-10.jpg'),
(184,'Lesser Black-backed Gull','Larus fuscus',28,'https://upload.wikimedia.org/wikipedia/commons/0/01/Goeland_adulte_et_juv%C3%A9nile.jpg'),
(185,'European Herring Gull','Larus argentatus',28,'https://upload.wikimedia.org/wikipedia/commons/8/8a/Larus_argentatus%2C_Vaxholm%2C_Stockholm%2C_Sweden_%2814923468303%29.jpg'),
(186,'Armenian Gull','Larus armenicus',28,'https://upload.wikimedia.org/wikipedia/commons/5/5e/3_Armenian_Gulls_-_front%2C_back_and_side_views.jpg'),
(187,'Yellow-legged Gull','Larus michahellis',28,'https://upload.wikimedia.org/wikipedia/commons/e/ed/2010.04.11_yellow-legged_gulls%2C_Constanta%2C_Romania_096cc.jpg'),
(188,'Caspian Gull','Larus cachinnans',28,'https://upload.wikimedia.org/wikipedia/commons/0/00/Caspian_gull_%28Larus_cachinnans%29_juvenile_Danube_delta.jpg'),
(189,'Iceland Gull','Larus glaucoides',28,'https://upload.wikimedia.org/wikipedia/commons/4/4d/20250105_iceland_gull_beaver_brook_open_space_PD200402.jpg'),
(190,'Great Black-backed Gull','Larus marinus',28,'https://upload.wikimedia.org/wikipedia/commons/d/d5/2024-06-01_01_Great_black-backed_gull_%28Larus_marinus%29_female_with_chicks.jpg'),
(191,'Bridled Tern','Onychoprion anaethetus',28,'https://upload.wikimedia.org/wikipedia/commons/b/bd/Bridled_Tern.jpg'),
(192,'Little Tern','Sternula albifrons',28,'https://upload.wikimedia.org/wikipedia/commons/9/9e/%D0%9A%D1%80%D1%8F%D1%87%D0%BE%D0%BA_%D0%BC%D0%B0%D0%BB%D0%B8%D0%B9.jpg'),
(193,'Common Gull-billed Tern','Gelochelidon nilotica',28,'https://upload.wikimedia.org/wikipedia/commons/a/a4/Gelochelidon_nilotica_vanrossemi.jpg'),
(194,'Caspian Tern','Hydroprogne caspia',28,'https://upload.wikimedia.org/wikipedia/commons/0/0a/Caspian_Tern_in_flight_in_New_Zealand.png'),
(195,'Whiskered Tern','Chlidonias hybrida',28,'https://upload.wikimedia.org/wikipedia/commons/2/2c/Chlidonias_hybrida_1_%28Marek_Szczepanek%29.jpg'),
(196,'White-winged Tern','Chlidonias leucopterus',28,'https://upload.wikimedia.org/wikipedia/commons/d/d0/Chlidonias_leucopterus_2023-04-08.jpg'),
(197,'Black Tern','Chlidonias niger',28,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Black_Tern_RWD.jpg'),
(198,'Common Tern','Sterna hirundo',28,'https://upload.wikimedia.org/wikipedia/commons/a/a6/2014-05-18_Sterna_hirundo%2C_Killingworth_Lake%2C_Northumberland_02.jpg'),
(199,'Arctic Tern','Sterna paradisaea',28,'https://upload.wikimedia.org/wikipedia/commons/2/29/2009_07_02_-_Arctic_tern_on_Farne_Islands_-_The_blue_rope_demarcates_the_visitors%27_path.JPG'),
(200,'Lesser Crested Tern','Sterna bengalensis',28,'https://upload.wikimedia.org/wikipedia/commons/2/24/Lesser_Crested_Tern_at_Kutch.jpg'),
(201,'Sandwich Tern','Sterna sandvicensis',28,'https://upload.wikimedia.org/wikipedia/commons/4/49/2020-07-18_Thalasseus_sandvicensis%2C_St_Marys_Island%2C_Northumberland_11.jpg'),
(202,'Long-tailed Jaeger','Stercorarius longicaudus',29,'https://upload.wikimedia.org/wikipedia/commons/b/b4/Long-tailed_Skua_in_flight.jpg'),
(203,'Arctic Jaeger','Stercorarius parasiticus',29,'https://upload.wikimedia.org/wikipedia/commons/4/4c/2021-07-11_Parasitic_jaeger_-_51358219005.jpg'),
(204,'Pomarine Jaeger','Stercorarius pomarinus',29,'https://upload.wikimedia.org/wikipedia/commons/0/0d/Stercorarius_pomarinusPCCA20070623-3985B.jpg'),
(205,'Great Skua','Stercorarius skua',29,'https://upload.wikimedia.org/wikipedia/commons/6/64/GreatSkuaInWater.jpg'),
(206,'Common Barn-owl','Tyto alba',30,'https://upload.wikimedia.org/wikipedia/commons/1/17/Barn_Owl%2C_Lancashire.jpg'),
(207,'Eurasian Pygmy-owl','Glaucidium passerinum',31,'https://upload.wikimedia.org/wikipedia/commons/7/79/Eurasian_pygmy_owl_%28Glaucidium_passerinum%29_Bia%C5%82owieza.jpg'),
(208,'Little Owl','Athene noctua',31,'https://upload.wikimedia.org/wikipedia/commons/5/51/Athene_noctua_%28Steenuilkuiken%29.jpg'),
(209,'Boreal Owl','Aegolius funereus',31,'https://upload.wikimedia.org/wikipedia/commons/1/17/Aegolius-funereus-001.jpg'),
(210,'Eurasian Scops-owl','Otus scops',31,'https://upload.wikimedia.org/wikipedia/commons/d/dc/Scops_Owl_%28Otus_scops%29%2C_Kalloni%2C_Lesvos%2C_Greece%2C_19.04.2015_%2816773748434%29.jpg'),
(211,'Northern Long-eared Owl','Asio otus',31,'https://upload.wikimedia.org/wikipedia/commons/9/97/Waldohreule_in_freier_Wildbahn.jpg'),
(212,'Short-eared Owl','Asio flammeus',31,'https://upload.wikimedia.org/wikipedia/commons/1/1a/Asio_flammeus_-Fazenda_Campo_de_Ouro%2C_Piraju%2C_Sao_Paulo%2C_Brasil-8.jpg'),
(213,'Tawny Owl','Strix aluco',31,'https://upload.wikimedia.org/wikipedia/commons/5/55/Strix_aluco_3_%28Martin_Mecnarowski%29.jpg'),
(214,'Ural Owl','Strix uralensis',31,'https://upload.wikimedia.org/wikipedia/commons/4/4b/Strix_uralensis_0a1.JPG'),
(215,'Eurasian Eagle-owl','Bubo bubo',31,'https://upload.wikimedia.org/wikipedia/commons/2/2d/1Puchacz_obronna_poza.jpg'),
(216,'Osprey','Pandion haliaetus',32,'https://upload.wikimedia.org/wikipedia/commons/c/c2/Osprey-27527-1.jpg'),
(217,'Black-winged Kite','Elanus caeruleus',33,'https://upload.wikimedia.org/wikipedia/commons/2/28/Black-shouldered_Kite_%28Elanus_caeruleus%29_in_Hyderabad_W_IMG_4418.jpg'),
(218,'European Honey-buzzard','Pernis apivorus',33,'https://upload.wikimedia.org/wikipedia/commons/b/be/%D0%9E%D1%81%D0%BE%D0%B5%D0%B4_%D0%93%D1%80%D0%BE%D0%B4%D0%BD%D0%BE.JPG'),
(219,'Bearded Vulture','Gypaetus barbatus',33,'https://upload.wikimedia.org/wikipedia/commons/1/1c/023_Wild_Bearded_Vulture_Switzerland_Pfyn-Finges_Photo_by_Giles_Laurent.jpg'),
(220,'Egyptian Vulture','Neophron percnopterus',33,'https://upload.wikimedia.org/wikipedia/commons/0/0a/Aasgier_%2848794413228%29_%28detail%29.jpg'),
(221,'Short-toed Snake-eagle','Circaetus gallicus',33,'https://upload.wikimedia.org/wikipedia/commons/5/52/Circaetus_gallicus_02.jpg'),
(222,'Griffon Vulture','Gyps fulvus',33,'https://upload.wikimedia.org/wikipedia/commons/9/95/Cinereous_Vulture_and_Eurasian_Griffon_%2850862528446%29.jpg'),
(223,'Cinereous Vulture','Aegypius monachus',33,'https://upload.wikimedia.org/wikipedia/commons/8/85/Aegypius_monachus.jpg'),
(224,'Lesser Spotted Eagle','Aquila pomarina',33,'https://upload.wikimedia.org/wikipedia/commons/7/7d/Lesser_Spotted_Eagle_Nationalpark_Bayerischer_Wald_01.jpg'),
(225,'Greater Spotted Eagle','Aquila clanga',33,'https://upload.wikimedia.org/wikipedia/commons/c/c5/A_Pesky_Drongo_Annoying_a_Greater_Spotted_Eagle_%2850877459286%29.jpg'),
(226,'Steppe Eagle','Aquila nipalensis',33,'https://upload.wikimedia.org/wikipedia/commons/2/27/20191213_Ptaki_padlino%C5%BCerne_w_rezerwacie_Jor_Beed_po_Bikanerem_0936_8329.jpg'),
(227,'Eastern Imperial Eagle','Aquila heliaca',33,'https://upload.wikimedia.org/wikipedia/commons/8/8a/Kaiseradler_Aquila_heliaca_e_amk.jpg'),
(228,'Golden Eagle','Aquila chrysaetos',33,'https://upload.wikimedia.org/wikipedia/commons/c/cc/015_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_%28Switzerland%29_Photo_by_Giles_Laurent.jpg'),
(229,'Bonelli''s Eagle','Aquila fasciata',33,'https://upload.wikimedia.org/wikipedia/commons/e/e8/Bonelli%27s_Eagle.jpg'),
(230,'Booted Eagle','Aquila pennata',33,'https://upload.wikimedia.org/wikipedia/commons/8/89/AquilaPennata.jpg'),
(231,'Western Marsh-harrier','Circus aeruginosus',33,'https://upload.wikimedia.org/wikipedia/commons/b/bb/Western_Marsh_Harrier.jpg'),
(232,'Hen Harrier','Circus cyaneus',33,'https://upload.wikimedia.org/wikipedia/commons/8/87/Wow2_filtered.jpg'),
(233,'Pallid Harrier','Circus macrourus',33,'https://upload.wikimedia.org/wikipedia/commons/e/e0/Pallid_Harrier_imported_from_iNaturalist_photo_389994827_on_16_June_2024.jpg'),
(234,'Montagu''s Harrier','Circus pygargus',33,'https://upload.wikimedia.org/wikipedia/commons/c/c4/Flickr_-_don_macauley_-_Bird_015.jpg'),
(235,'Levant Sparrowhawk','Accipiter brevipes',33,'https://upload.wikimedia.org/wikipedia/commons/a/a4/Accipiter_brevipes%2C_male.jpg'),
(236,'Eurasian Sparrowhawk','Accipiter nisus',33,'https://upload.wikimedia.org/wikipedia/commons/d/d0/Accipiter_nisus_Meneer_Zjeroen.jpg'),
(237,'Northern Goshawk','Accipiter gentilis',33,'https://upload.wikimedia.org/wikipedia/commons/4/4e/Acc_nest.jpg'),
(238,'White-tailed Sea-eagle','Haliaeetus albicilla',33,'https://upload.wikimedia.org/wikipedia/commons/e/ef/Adult_white-tailed_eagle_as_decoy_near_Qinhuangdao.jpg'),
(239,'Red Kite','Milvus milvus',33,'https://upload.wikimedia.org/wikipedia/commons/4/49/Milvus_milvus_Jura.jpg'),
(240,'Black Kite','Milvus migrans',33,'https://upload.wikimedia.org/wikipedia/commons/6/65/1J6A4281-Black_Kite.jpg'),
(241,'Rough-legged Buzzard','Buteo lagopus',33,'https://upload.wikimedia.org/wikipedia/commons/e/e4/Buteo_lagopus_29283.JPG'),
(242,'Eurasian Buzzard','Buteo buteo',33,'https://upload.wikimedia.org/wikipedia/commons/c/cd/Buteo_buteo_-Netherlands-8.jpg'),
(243,'Long-legged Buzzard','Buteo rufinus',33,'https://upload.wikimedia.org/wikipedia/commons/e/ed/Arendbuizerd-1_%2815579048937%29.jpg'),
(244,'Common Hoopoe','Upupa epops',34,'https://upload.wikimedia.org/wikipedia/commons/d/d3/ABUBILLA_%28Upupa_epops%29.jpg'),
(245,'Asian Green Bee-eater','Merops orientalis',35,'https://upload.wikimedia.org/wikipedia/commons/3/34/Asian_green_bee-eater_%28Merops_orientalis_beludschicus%29_dust_bathing_near_Roorkee%2C_Haridwar_district.jpg'),
(246,'Blue-cheeked Bee-eater','Merops persicus',35,'https://upload.wikimedia.org/wikipedia/commons/4/4c/Blue-cheeked_bee-eater_%28Merops_persicus_chrysocercus%29.jpg'),
(247,'European Bee-eater','Merops apiaster',35,'https://upload.wikimedia.org/wikipedia/commons/7/7a/European_bee_eater.jpg'),
(248,'European Roller','Coracias garrulus',36,'https://upload.wikimedia.org/wikipedia/commons/d/d2/Arrival_%2847961559816%29.jpg'),
(249,'Common Kingfisher','Alcedo atthis',37,'https://upload.wikimedia.org/wikipedia/commons/b/bc/Alcedo_atthis_-England-8_%28cropped%29.jpg'),
(250,'Pied Kingfisher','Ceryle rudis',37,'https://upload.wikimedia.org/wikipedia/commons/e/e4/Pied_kingfisher.jpg'),
(251,'White-breasted Kingfisher','Halcyon smyrnensis',37,'https://upload.wikimedia.org/wikipedia/commons/3/31/White-throated-Kingfisher.jpg'),
(252,'Eurasian Wryneck','Jynx torquilla',38,'https://upload.wikimedia.org/wikipedia/commons/1/10/Jynx_torquilla_-Norway-8_%281%29.jpg'),
(253,'Grey-faced Woodpecker','Picus canus',38,'https://upload.wikimedia.org/wikipedia/commons/4/4a/Grey-headed_Woodpecker_2.jpg'),
(254,'Eurasian Green Woodpecker','Picus viridis',38,'https://upload.wikimedia.org/wikipedia/commons/c/c5/European_green_woodpecker_%28Picus_viridis%29_female_Barnes.jpg'),
(255,'Black Woodpecker','Dryocopus martius',38,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Black_Woodpecker_taking_an_ant_bath_-_HungaryCS4E4536_%2815788008504%29.jpg'),
(256,'Three-toed Woodpecker','Picoides tridactylus',38,'https://upload.wikimedia.org/wikipedia/commons/0/04/Three-toed_Woodpecker_-_Finlandia_0005_%283%29.jpg'),
(257,'Middle Spotted Woodpecker','Dendrocopos medius',38,'https://upload.wikimedia.org/wikipedia/commons/d/d0/DendrocoposMediusSanctijohannis.jpg'),
(258,'Lesser Spotted Woodpecker','Dendrocopos minor',38,'https://upload.wikimedia.org/wikipedia/commons/3/33/DendrocoposMinorNaturalHabitat.jpg'),
(259,'White-backed Woodpecker','Dendrocopos leucotos',38,'https://upload.wikimedia.org/wikipedia/commons/b/b6/Dendrocopos_leucotos_2.jpg'),
(260,'Syrian Woodpecker','Dendrocopos syriacus',38,'https://upload.wikimedia.org/wikipedia/commons/1/13/Dendrocopos_syriacus.jpg'),
(261,'Great Spotted Woodpecker','Dendrocopos major',38,'https://upload.wikimedia.org/wikipedia/commons/a/ab/Dendrocopos_major_-London%2C_England_-female_feeding_chick-8.jpg'),
(262,'Lesser Kestrel','Falco naumanni',39,'https://upload.wikimedia.org/wikipedia/commons/c/ce/Falco_naumanni%2C_Negev_1.jpg'),
(263,'Common Kestrel','Falco tinnunculus',39,'https://upload.wikimedia.org/wikipedia/commons/5/5c/Common-Kestrel-2.jpg'),
(264,'Red-footed Falcon','Falco vespertinus',39,'https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotfu%C3%9Ffalke_Falco_vespertinus.jpg'),
(265,'Amur Falcon','Falco amurensis',39,'https://upload.wikimedia.org/wikipedia/commons/9/94/Amur_Falcon_%28F%29.jpg'),
(266,'Eleonora''s Falcon','Falco eleonorae',39,'https://upload.wikimedia.org/wikipedia/commons/d/d8/Eleonora%27s_falcon_%28Falco_eleonorae%29_in_flight_3.jpg'),
(267,'Merlin','Falco columbarius',39,'https://upload.wikimedia.org/wikipedia/commons/d/d6/Falco_columbarius_Male.jpg'),
(268,'Eurasian Hobby','Falco subbuteo',39,'https://upload.wikimedia.org/wikipedia/commons/d/df/Eurasian_hobby_%28Falco_subbuteo%29_by_Shantanu_Kuveskar.jpg'),
(269,'Lanner Falcon','Falco biarmicus',39,'https://upload.wikimedia.org/wikipedia/commons/3/3c/Falco_biarmicus_Etosha.jpg'),
(270,'Saker Falcon','Falco cherrug',39,'https://upload.wikimedia.org/wikipedia/commons/d/d4/Falco_cherrug_1_%28Bohu%C5%A1_%C4%8C%C3%AD%C4%8Del%29.jpg'),
(271,'Peregrine Falcon','Falco peregrinus',39,'https://upload.wikimedia.org/wikipedia/commons/1/1e/Peregrine_Falcon_in_flight.jpg'),
(272,'Barbary Falcon','Falco pelegrinoides',39,'https://upload.wikimedia.org/wikipedia/commons/3/39/Barbary_Falcon%2C_%22El_Rubic%C3%B3n%22_plains%2C_Lanzarote.jpg'),
(273,'Rose-ringed Parakeet','Psittacula krameri',40,'https://upload.wikimedia.org/wikipedia/commons/b/b9/2013.07.15.-3-Vogelstangsee_Mannheim-Halsbandsittich-Weibchen.jpg'),
(274,'Eurasian Golden Oriole','Oriolus oriolus',41,'https://upload.wikimedia.org/wikipedia/commons/c/cf/Loriot_d%27Europe_-_Flickr_-_Philippe_Garcelon%2C_crop.jpg'),
(275,'Red-backed Shrike','Lanius collurio',42,'https://upload.wikimedia.org/wikipedia/commons/7/77/Neuntoeter-Jungvogel.jpg'),
(276,'Red-tailed Shrike','Lanius phoenicuroides',42,'https://upload.wikimedia.org/wikipedia/commons/4/4d/0T4A6719.jpg'),
(277,'Isabelline Shrike','Lanius isabellinus',42,'https://upload.wikimedia.org/wikipedia/commons/a/a4/Isabelline_Shrike_%2815214160368%29.jpg'),
(278,'Lesser Grey Shrike','Lanius minor',42,'https://upload.wikimedia.org/wikipedia/commons/0/0c/Lesser_Grey_Shrike_by_Daniel_Bastaja.jpg'),
(279,'Great Grey Shrike','Lanius excubitor',42,'https://upload.wikimedia.org/wikipedia/commons/4/44/Lanius_excubitor_1_%28Marek_Szczepanek%29.jpg'),
(280,'Iberian Grey Shrike','Lanius meridionalis',42,'https://upload.wikimedia.org/wikipedia/commons/e/e8/Lanius_meridionalis%2C_P%C3%AAra%2C_Algarve%2C_Portugal_1_%28cropped%29.jpg'),
(281,'Woodchat Shrike','Lanius senator',42,'https://upload.wikimedia.org/wikipedia/commons/1/1c/Alcaud%C3%B3n_com%C3%BAn_%28Lanius_senator%29_%288587246504%29_%282%29.jpg'),
(282,'Masked Shrike','Lanius nubicus',42,'https://upload.wikimedia.org/wikipedia/commons/6/6a/Lanius_nubicus_%28unmirrored%29.jpg'),
(283,'Red-billed Chough','Pyrrhocorax pyrrhocorax',43,'https://upload.wikimedia.org/wikipedia/commons/0/05/Alpenkr%C3%A4he-Pyrrhocorax.jpg'),
(284,'Yellow-billed Chough','Pyrrhocorax graculus',43,'https://upload.wikimedia.org/wikipedia/commons/2/2d/Alpine_Chough_by_Jim_Higham.jpg'),
(285,'Eurasian Jay','Garrulus glandarius',43,'https://upload.wikimedia.org/wikipedia/commons/a/a9/Cyprus_jay_%28Garrulus_glandarius_glaszneri%29.jpg'),
(286,'Eurasian Magpie','Pica pica',43,'https://upload.wikimedia.org/wikipedia/commons/b/b6/Pica_pica_-_Compans_Caffarelli_-_2012-03-16.jpg'),
(287,'Northern Nutcracker','Nucifraga caryocatactes',43,'https://upload.wikimedia.org/wikipedia/commons/c/c5/Guest_from_the_taiga.jpg'),
(288,'Eurasian Jackdaw','Corvus monedula',43,'https://upload.wikimedia.org/wikipedia/commons/7/7e/2013_Fliegende_Dohle.JPG'),
(289,'Rook','Corvus frugilegus',43,'https://upload.wikimedia.org/wikipedia/commons/0/0f/Corvus_frugilegus-profile.jpg'),
(290,'Common Raven','Corvus corax',43,'https://upload.wikimedia.org/wikipedia/commons/5/50/Corvus_corax_ad_berlin_090516.jpg'),
(291,'Carrion Crow','Corvus corone',43,'https://upload.wikimedia.org/wikipedia/commons/a/a9/Corvus_corone_-near_Canford_Cliffs%2C_Poole%2C_England-8.jpg'),
(292,'Coal Tit','Periparus ater',44,'https://upload.wikimedia.org/wikipedia/commons/e/ee/Coal_tit_%28Periparus_ater%29_on_line.jpeg'),
(293,'Crested Tit','Lophophanes cristatus',44,'https://upload.wikimedia.org/wikipedia/commons/8/8f/Lophophanes_cristatus_-Aviemore%2C_Scotland-8.jpg'),
(294,'Sombre Tit','Poecile lugubris',44,'https://upload.wikimedia.org/wikipedia/commons/7/7d/Poecile_lugubris%2C_Bulgaria_1.jpg'),
(295,'Marsh Tit','Poecile palustris',44,'https://upload.wikimedia.org/wikipedia/commons/3/3a/Parus_palustris02.jpg'),
(296,'Willow Tit','Poecile montanus',44,'https://upload.wikimedia.org/wikipedia/commons/1/13/Poecile_montanus_kleinschmidti.jpg'),
(297,'Eurasian Blue Tit','Cyanistes caeruleus',44,'https://upload.wikimedia.org/wikipedia/commons/c/ce/A_bald_blue_tit_with_mite.jpg'),
(298,'Great Tit','Parus major',44,'https://upload.wikimedia.org/wikipedia/commons/6/65/Parus_major_2_Luc_Viatour.jpg'),
(299,'Eurasian Penduline-tit','Remiz pendulinus',45,'https://upload.wikimedia.org/wikipedia/commons/5/5e/Auriparus_flaviceps.jpg'),
(300,'Dupont''s Lark','Chersophilus duponti',46,'https://upload.wikimedia.org/wikipedia/commons/c/c8/Dupont%27s_Lark%2C_Morocco_1_%28crop%29_%28cropped%29.jpg'),
(301,'Lesser Short-toed Lark','Calandrella rufescens',46,'https://upload.wikimedia.org/wikipedia/commons/b/b8/Calandrella_rufescens_-Canary_Islands_-Spain-8.jpg'),
(302,'Bimaculated Lark','Melanocorypha bimaculata',46,'https://upload.wikimedia.org/wikipedia/commons/f/ff/Melanocorypha_bimaculata_117209398.jpg'),
(303,'Calandra Lark','Melanocorypha calandra',46,'https://upload.wikimedia.org/wikipedia/commons/7/7b/Bere%C5%9Fe.jpg'),
(304,'Black Lark','Melanocorypha yeltoniensis',46,'https://upload.wikimedia.org/wikipedia/commons/4/45/Black_Lark_-_Kazakistan_S4E9836_%2816946135312%29-cropped.jpg'),
(305,'Greater Short-toed Lark','Calandrella brachydactyla',46,'https://upload.wikimedia.org/wikipedia/commons/8/8d/Alouette_calandrelle_ichkeul001.jpg'),
(306,'Horned Lark','Eremophila alpestris',46,'https://upload.wikimedia.org/wikipedia/commons/d/d7/Bergl%C3%A4rka-Eremophila_alpestris.jpg'),
(307,'Woodlark','Lullula arborea',46,'https://upload.wikimedia.org/wikipedia/commons/3/32/Heidelerche_%281%29.JPG'),
(308,'White-winged Lark','Melanocorypha leucoptera',46,'https://upload.wikimedia.org/wikipedia/commons/5/5d/Alauda_leucoptera_57392188.jpg'),
(309,'Eurasian Skylark','Alauda arvensis',46,'https://upload.wikimedia.org/wikipedia/commons/d/d6/20240609_Feldlerche_%28Alauda_arvensis%29.jpg'),
(310,'Crested Lark','Galerida cristata',46,'https://upload.wikimedia.org/wikipedia/commons/1/15/Cochevis_hupp%C3%A9_Gbollat.jpg'),
(311,'Bearded Reedling','Panurus biarmicus',47,'https://upload.wikimedia.org/wikipedia/commons/8/8f/Bartmeise_im_NSG_Federsee_04.jpg'),
(312,'Zitting Cisticola','Cisticola juncidis',48,'https://upload.wikimedia.org/wikipedia/commons/3/31/Zitting_cisticola_2024_04_19_%28cropped%29.jpg'),
(313,'Booted Warbler','Iduna caligata',49,'https://upload.wikimedia.org/wikipedia/commons/2/2f/Booted_Warbler%2C_Iduna_caligata.jpg'),
(314,'Olivaceous Warbler','Iduna pallida',49,'https://upload.wikimedia.org/wikipedia/commons/e/e7/Eastern_olivaceous_warbler_%28Iduna_pallida%29_by_Lior_Kislev.jpg'),
(315,'Isabelline Warbler','Iduna opaca',49,'https://upload.wikimedia.org/wikipedia/commons/8/85/Iduna_opaca_CDC_image.jpg'),
(316,'Olive-tree Warbler','Hippolais olivetorum',49,'https://upload.wikimedia.org/wikipedia/commons/7/7c/Olive-tree_warbler%2C_Hippolais_olivetorum%2C_at_Mkuze_Game_Reserve%2C_%2839230388474%29.jpg'),
(317,'Melodious Warbler','Hippolais polyglotta',49,'https://upload.wikimedia.org/wikipedia/commons/c/ca/Melodious_Warbler_2025_05_23.jpg'),
(318,'Icterine Warbler','Hippolais icterina',49,'https://upload.wikimedia.org/wikipedia/commons/9/9e/Icterine_warbler_18_06_2022_004_crop.png'),
(319,'Aquatic Warbler','Acrocephalus paludicola',49,'https://upload.wikimedia.org/wikipedia/commons/1/1d/Seggenrohrsaenger_hand.jpg'),
(320,'Moustached Warbler','Acrocephalus melanopogon',49,'https://upload.wikimedia.org/wikipedia/commons/e/ec/Moustached_Warbler_Acrocephalus_melanopogon_by_Dr._Raju_Kasambe_%282%29.jpg'),
(321,'Sedge Warbler','Acrocephalus schoenobaenus',49,'https://upload.wikimedia.org/wikipedia/commons/b/b9/Acrocephalus_schoenobaenus_%28in_habitat%29.jpg'),
(322,'Marsh Warbler','Acrocephalus palustris',49,'https://upload.wikimedia.org/wikipedia/commons/9/96/Acrocephalus_palustris_Irpin6.JPG'),
(323,'Common Reed-warbler','Acrocephalus scirpaceus',49,'https://upload.wikimedia.org/wikipedia/commons/2/24/PleidelsheimerWiesentalTeichrohrsaenger.jpg'),
(324,'Paddyfield Warbler','Acrocephalus agricola',49,'https://upload.wikimedia.org/wikipedia/commons/7/74/Paddyfield_Warbler_%28Acrocephalus_agricola%29_in_Kolkata_Im_IMG_0496.jpg'),
(325,'Great Reed-warbler','Acrocephalus arundinaceus',49,'https://upload.wikimedia.org/wikipedia/commons/0/03/Drosselrohrs%C3%A4nger_Great_reed_warbler.jpg'),
(326,'Savi''s Warbler','Locustella luscinioides',50,'https://upload.wikimedia.org/wikipedia/commons/8/84/Locustellaluscinioides.jpg'),
(327,'River Warbler','Locustella fluviatilis',50,'https://upload.wikimedia.org/wikipedia/commons/d/de/Flodsangare.jpg'),
(328,'Common Grasshopper-warbler','Locustella naevia',50,'https://upload.wikimedia.org/wikipedia/commons/b/b0/Grasshopper_Warbler_Locustella_naevia_by_Dr._Raju_Kasambe.jpg'),
(329,'Northern House Martin','Delichon urbicum',51,'https://upload.wikimedia.org/wikipedia/commons/1/12/A_mother_flying_back_to_housemartin_nest.jpg'),
(330,'Red-rumped Swallow','Cecropis daurica',51,'https://upload.wikimedia.org/wikipedia/commons/1/19/Eastern_red-rumped_swallow.jpg'),
(331,'Barn Swallow','Hirundo rustica',51,'https://upload.wikimedia.org/wikipedia/commons/4/42/A_reflection_flight_of_barn_swallow.jpg'),
(332,'Eurasian Crag Martin','Ptyonoprogne rupestris',51,'https://upload.wikimedia.org/wikipedia/commons/6/62/Cragmartinnest.jpg'),
(333,'Collared Sand Martin','Riparia riparia',51,'https://upload.wikimedia.org/wikipedia/commons/e/ee/Riparia_Riparia-2006-Ejdzej-1.jpg'),
(334,'Eastern Bonelli''s Warbler','Phylloscopus orientalis',52,'https://upload.wikimedia.org/wikipedia/commons/c/cb/Eastern_Bonelli%27s_Warbler.jpg'),
(335,'Western Bonelli''s Warbler','Phylloscopus bonelli',52,'https://upload.wikimedia.org/wikipedia/commons/4/47/Western_Bonelli%27s_Warbler_-_Aosta_Valley_-_Italy_S4E5346_%2819079885220%29.jpg'),
(336,'Wood Warbler','Phylloscopus sibilatrix',52,'https://upload.wikimedia.org/wikipedia/commons/e/e0/Flickr_-_Rainbirder_-_Wood_Warbler_%28Phylloscopus_sibilatrix%29.jpg'),
(337,'Yellow-browed Warbler','Phylloscopus inornatus',52,'https://upload.wikimedia.org/wikipedia/commons/5/52/Ch%C3%ADch_m%C3%A0y_l%E1%BB%9Bn.jpg'),
(338,'Hume''s Leaf-warbler','Phylloscopus humei',52,'https://upload.wikimedia.org/wikipedia/commons/1/1d/Hume%27s_Warbler_I2_IMG_3401.jpg'),
(339,'Pallas''s Leaf-warbler','Phylloscopus proregulus',52,'https://upload.wikimedia.org/wikipedia/commons/0/04/Pallas%27s_Leaf_Warbler%2C_Tunkinskiy_Rayon%2C_Buryat%2C_Russia_2.jpg'),
(340,'Dusky Warbler','Phylloscopus fuscatus',52,'https://upload.wikimedia.org/wikipedia/commons/d/d6/DuskyWarbler_Cropped.jpg'),
(341,'Willow Warbler','Phylloscopus trochilus',52,'https://upload.wikimedia.org/wikipedia/commons/5/5b/Willow_Warbler_Phylloscopus_trochilus.jpg'),
(342,'Iberian Chiffchaff','Phylloscopus ibericus',52,'https://upload.wikimedia.org/wikipedia/commons/2/24/Phylloscopus_ibericus.jpg'),
(343,'Common Chiffchaff','Phylloscopus collybita',52,'https://upload.wikimedia.org/wikipedia/commons/c/cc/Chiffchaff_-_Phylloscopus_collybita.jpg'),
(344,'Greenish Warbler','Phylloscopus nitidus',52,'https://upload.wikimedia.org/wikipedia/commons/8/88/Green_warbler.jpg'),
(345,'Arctic Warbler','Phylloscopus borealis',52,'https://upload.wikimedia.org/wikipedia/commons/3/33/Arctic_Warbler_4683b.jpg'),
(346,'Cetti''s Warbler','Cettia cetti',53,'https://upload.wikimedia.org/wikipedia/commons/7/73/37-090505-cettis-warbler-at-Kalloni-east-river.jpg'),
(347,'Long-tailed Tit','Aegithalos caudatus',54,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Aegithalos_caudatus_vogelartinfo_chris_romeiks_R7F2607.jpg'),
(348,'Eurasian Blackcap','Sylvia atricapilla',55,'https://upload.wikimedia.org/wikipedia/commons/f/f5/Blackcap_%28Sylvia_atricapilla%29_male.jpg'),
(349,'Garden Warbler','Sylvia borin',55,'https://upload.wikimedia.org/wikipedia/commons/0/07/Sylvia_borin_%28%C3%96rebro_County%29.jpg'),
(350,'Barred Warbler','Sylvia nisoria',55,'https://upload.wikimedia.org/wikipedia/commons/d/da/Barred_Warbler_%28Sylvia_nisoria%29_-_geograph.org.uk_-_1036172.jpg'),
(351,'Eastern Orphean Warbler','Sylvia crassirostris',55,'https://upload.wikimedia.org/wikipedia/commons/8/84/Curruca_crassirostris_91619419_%28cropped%29.jpg'),
(352,'Lesser Whitethroat','Sylvia curruca',55,'https://upload.wikimedia.org/wikipedia/commons/7/74/%D0%A1%D0%BB%D0%B0%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%88%D0%BA%D0%B0_%28Sylvia_curruca%29.jpg'),
(353,'Sardinian Warbler','Sylvia melanocephala',55,'https://upload.wikimedia.org/wikipedia/commons/e/e1/Sardinian_Warbler.jpg'),
(354,'Subalpine Warbler','Sylvia cantillans',55,'https://upload.wikimedia.org/wikipedia/commons/a/a9/%CE%9A%CE%BF%CE%BA%CE%BA%CE%B9%CE%BD%CE%BF%CF%84%CF%83%CE%B9%CF%81%CE%BF%CE%B2%CE%AC%CE%BA%CE%BF%CF%82.jpg'),
(355,'Western Subalpine Warbler','Sylvia inornata',55,'https://upload.wikimedia.org/wikipedia/commons/5/5c/Subalpine_Warbler_-_Monfrague_-_Spain_2669_%2819110069408%29.jpg'),
(356,'Rüppell''s Warbler','Sylvia rueppelli',55,'https://upload.wikimedia.org/wikipedia/commons/0/08/Ruppell%27s_warbler.jpg'),
(357,'Common Whitethroat','Sylvia communis',55,'https://upload.wikimedia.org/wikipedia/commons/9/91/Common_Whitethroat.jpg'),
(358,'Spectacled Warbler','Sylvia conspicillata',55,'https://upload.wikimedia.org/wikipedia/commons/c/c1/Fauvette_%C3%A0_lunettes_Aqueduc_de_Zaghouan.jpg'),
(359,'Marmora''s Warbler','Sylvia sarda',55,'https://upload.wikimedia.org/wikipedia/commons/d/d2/Marmora%27s_Warbler_-_Sardinia_-_Italy_S4E1036.jpg'),
(360,'Dartford Warbler','Sylvia undata',55,'https://upload.wikimedia.org/wikipedia/commons/4/47/Dartford_Warbler_-_Ligura_-_Italy_S4E3711_%2818675159154%29.jpg'),
(361,'Short-toed Treecreeper','Certhia brachydactyla',56,'https://upload.wikimedia.org/wikipedia/commons/0/0d/Short-toed_treecreeper_%28Certhia_brachydactyla_megarhynchos%29.jpg'),
(362,'Eurasian Treecreeper','Certhia familiaris',56,'https://upload.wikimedia.org/wikipedia/commons/c/c3/474px-Certhia_familiariscroppedmirror.jpg'),
(363,'Eurasian Nuthatch','Sitta europaea',57,'https://upload.wikimedia.org/wikipedia/commons/2/21/Eurasian_nuthatch_%28Sitta_europaea_caesia%29.jpg'),
(364,'Krueper''s Nuthatch','Sitta krueperi',57,'https://upload.wikimedia.org/wikipedia/commons/7/7c/Algerian_nuthatch_by_Aissa_Djamel_Filali_%28cropped%29.jpg'),
(365,'Western Rock Nuthatch','Sitta neumayer',57,'https://upload.wikimedia.org/wikipedia/commons/b/bc/Westernrocknuthatch_Sitta_neumayer.jpg'),
(366,'Wallcreeper','Tichodroma muraria',57,'https://upload.wikimedia.org/wikipedia/commons/1/1e/Picchio_Muraiolo_in_volo.jpg'),
(367,'Northern Wren','Troglodytes troglodytes',58,'https://upload.wikimedia.org/wikipedia/commons/8/80/%CE%A4%CF%81%CF%85%CF%80%CE%BF%CF%86%CF%81%CE%AC%CF%87%CF%84%CE%B7%CF%82_Troglodytes_troglodytes.jpg'),
(368,'White-throated Dipper','Cinclus cinclus',59,'https://upload.wikimedia.org/wikipedia/commons/6/6d/Cinclus_cinclus_-Brandon_Creek%2C_County_Kerry%2C_Ireland-8.jpg'),
(369,'Common Starling','Sturnus vulgaris',60,'https://upload.wikimedia.org/wikipedia/commons/7/7e/A_Common_Starling_on_the_ground%2C_D%C3%BCsseldorf.jpg'),
(370,'Spotless Starling','Sturnus unicolor',60,'https://upload.wikimedia.org/wikipedia/commons/a/a3/Estornino_Negro._Casa_de_Campo._Madrid_%283%29.jpg'),
(371,'Rosy Starling','Pastor roseus',60,'https://upload.wikimedia.org/wikipedia/commons/3/37/Ayleme_%281%29.jpg'),
(372,'Scaly Thrush','Zoothera dauma',61,'https://upload.wikimedia.org/wikipedia/commons/8/83/Scaly_Thrush_0A2A8657.jpg'),
(373,'Mistle Thrush','Turdus viscivorus',61,'https://upload.wikimedia.org/wikipedia/commons/4/48/2020-01-01_Mistle_Thrush_with_Rowan_berries%2C_Jesmond_Dene_1.jpg'),
(374,'Song Thrush','Turdus philomelos',61,'https://upload.wikimedia.org/wikipedia/commons/8/83/2007.07.03_juvenile_song_thrush_Dombaih%2C_Russia_108_cc.jpg'),
(375,'Redwing','Turdus iliacus',61,'https://upload.wikimedia.org/wikipedia/commons/f/f8/Redwing.jpg'),
(376,'Eurasian Blackbird','Turdus merula',61,'https://upload.wikimedia.org/wikipedia/commons/c/ce/Amsel_Weibchen_aufgeplustert_edit2.jpg'),
(377,'Fieldfare','Turdus pilaris',61,'https://upload.wikimedia.org/wikipedia/commons/6/68/Fieldfare_flock.JPG'),
(378,'Ring Ouzel','Turdus torquatus',61,'https://upload.wikimedia.org/wikipedia/commons/d/dd/2015-04-20_Turdus_torquatus_torquatus_Cairngorm_3.jpg'),
(379,'Rufous-throated Thrush','Turdus atrogularis',61,'https://upload.wikimedia.org/wikipedia/commons/2/28/A_dark-throated_Thrush_female_-_Dhanachuli%2C_Uttarakhand_India.jpg'),
(380,'Rufous-tailed Scrub-robin','Cercotrichas galactotes',62,'https://upload.wikimedia.org/wikipedia/commons/b/b0/Agrobate_roux_au_Parc_National_de_l%27Ichkeul_%28Tunisia%29%2C_crop.jpg'),
(381,'Asian Brown Flycatcher','Muscicapa dauurica',62,'https://upload.wikimedia.org/wikipedia/commons/d/df/Asian_Brown_Flycatcher_%28Muscicapa_dauurica%29_at_Periyar_National_Park.jpg'),
(382,'Spotted Flycatcher','Muscicapa striata',62,'https://upload.wikimedia.org/wikipedia/commons/2/25/Muscicapa_striata_1_%28Martin_Mecnarowski%29.jpg'),
(383,'European Robin','Erithacus rubecula',62,'https://upload.wikimedia.org/wikipedia/commons/b/b0/Erithacus_rubecula_-Canary_Islands%2C_Spain_-adult_and_juvenile-8.jpg'),
(384,'White-throated Robin','Irania gutturalis',62,'https://upload.wikimedia.org/wikipedia/commons/3/33/White_throat_Robin.jpg'),
(385,'Bluethroat','Luscinia svecica',62,'https://upload.wikimedia.org/wikipedia/commons/4/44/Blue_throat_at_Rajkot.jpg'),
(386,'Thrush Nightingale','Luscinia luscinia',62,'https://upload.wikimedia.org/wikipedia/commons/2/2c/Luscinia_luscinia_-Gugny%2C_Biebrza_National_Park%2C_Poland-8.jpg'),
(387,'Common Nightingale','Luscinia megarhynchos',62,'https://upload.wikimedia.org/wikipedia/commons/6/6f/Luscinia_megarhynchos_-_Common_nightingale_-_Nachtegaal.jpg'),
(388,'Red-breasted Flycatcher','Ficedula parva',62,'https://upload.wikimedia.org/wikipedia/commons/7/74/Red_brested_flycatcher_by_David_Raju_%28cropped%29.jpg'),
(389,'Semi-collared Flycatcher','Ficedula semitorquata',62,'https://upload.wikimedia.org/wikipedia/commons/0/0a/Ficedula_semitorquata.jpg'),
(390,'European Pied Flycatcher','Ficedula hypoleuca',62,'https://upload.wikimedia.org/wikipedia/commons/5/53/Ficedula_hypoleuca_-Wood_of_Cree_Nature_Reserve%2C_Scotland_-male-8a.jpg'),
(391,'Collared Flycatcher','Ficedula albicollis',62,'https://upload.wikimedia.org/wikipedia/commons/0/00/Collared_flycatcher_%28Ficedula_albicollis%29.jpg'),
(392,'Black Redstart','Phoenicurus ochruros',62,'https://upload.wikimedia.org/wikipedia/commons/2/2e/Black_Redstart_%28Phoenicurus_ochruros%29-_Male_at_Sultanpur_I_Picture1042.jpg'),
(393,'Common Redstart','Phoenicurus phoenicurus',62,'https://upload.wikimedia.org/wikipedia/commons/4/40/Gartenrotschwanz_1.jpg'),
(394,'Moussier''s Redstart','Phoenicurus moussieri',62,'https://upload.wikimedia.org/wikipedia/commons/d/d4/Moussier%27s_redstart_%28Phoenicurus_moussieri%29_male.jpg'),
(395,'Rufous-tailed Rock-thrush','Monticola saxatilis',62,'https://upload.wikimedia.org/wikipedia/commons/9/9d/Common_rock_thrush.jpg'),
(396,'Blue Rock-thrush','Monticola solitarius',62,'https://upload.wikimedia.org/wikipedia/commons/8/81/BlueRock-Thrush.jpg'),
(397,'Whinchat','Saxicola rubetra',62,'https://upload.wikimedia.org/wikipedia/commons/c/cb/Whinchat_-_Saxicola_rubetra_%28Male%29_%2852943525534%29.jpg'),
(398,'Eastern Stonechat','Saxicola maurus',62,'https://upload.wikimedia.org/wikipedia/commons/6/65/Asian_stonechat_%28Saxicola_maurus_indicus%29_male_non_breeding_Bardiya.jpg'),
(399,'Common Stonechat','Saxicola rubicola',62,'https://upload.wikimedia.org/wikipedia/commons/d/d7/Stonechat_%28Saxicola_rubicola%29_male%2C_Beaulieu%2C_Hampshire.jpg'),
(400,'Northern Wheatear','Oenanthe oenanthe',62,'https://upload.wikimedia.org/wikipedia/commons/1/17/Northern_wheatear_Oenanthe_oenanthe.jpg'),
(401,'Isabelline Wheatear','Oenanthe isabellina',62,'https://upload.wikimedia.org/wikipedia/commons/b/b4/Isabelline_wheatear_%28Oenanthe_isabellina%29_male%2C_non-breeding.jpg'),
(402,'Hooded Wheatear','Oenanthe monacha',62,'https://upload.wikimedia.org/wikipedia/commons/9/9e/Hooded_Wheatear.jpg'),
(403,'Desert Wheatear','Oenanthe deserti',62,'https://upload.wikimedia.org/wikipedia/commons/9/97/1J6A1397-Desert_Wheatear.jpg'),
(404,'Black-eared Wheatear','Oenanthe hispanica',62,'https://upload.wikimedia.org/wikipedia/commons/d/d4/CollalbaRubia.jpg'),
(405,'Pied Wheatear','Oenanthe pleschanka',62,'https://upload.wikimedia.org/wikipedia/commons/5/50/BGOenantheOenantheFemale.jpg'),
(406,'Black Wheatear','Oenanthe leucura',62,'https://upload.wikimedia.org/wikipedia/commons/d/db/Black_Wheatear_-_Merzouga_Marocco_07_3429_%2819400616192%29.jpg'),
(407,'White-crowned Wheatear','Oenanthe leucopyga',62,'https://upload.wikimedia.org/wikipedia/commons/e/e0/Israel._White-crowned_wheatear_%2815787696376%29.jpg'),
(408,'Finsch''s Wheatear','Oenanthe finschii',62,'https://upload.wikimedia.org/wikipedia/commons/8/89/%C3%87ilfer%C5%9Fik.jpg'),
(409,'Goldcrest','Regulus regulus',63,'https://upload.wikimedia.org/wikipedia/commons/3/3b/Regulus_regulus_60North_cropped.jpg'),
(410,'Common Firecrest','Regulus ignicapilla',63,'https://upload.wikimedia.org/wikipedia/commons/b/b9/Common_firecrest_Franconville_03.jpg'),
(411,'Bohemian Waxwing','Bombycilla garrulus',64,'https://upload.wikimedia.org/wikipedia/commons/1/16/Bombycilla_garrulus%2C_Novosibirsk_1.jpg'),
(412,'Alpine Accentor','Prunella collaris',65,'https://upload.wikimedia.org/wikipedia/commons/f/f0/Alpine_Accentor_Lungthu_Pangolakha_WLS_East_Sikkim_India_08.11.2015.jpg'),
(413,'Dunnock','Prunella modularis',65,'https://upload.wikimedia.org/wikipedia/commons/4/4e/Dunnock_%28Prunella_modularis%29_3.jpg'),
(414,'House Sparrow','Passer domesticus',66,'https://upload.wikimedia.org/wikipedia/commons/4/43/Alpenquai_Z%C3%BCrich_-_Passer_domesticus_2014-09-15_17-37-56.JPG'),
(415,'Spanish Sparrow','Passer hispaniolensis',66,'https://upload.wikimedia.org/wikipedia/commons/7/7d/Passer_Hispaniolensis_Male.JPG'),
(416,'Dead Sea Sparrow','Passer moabiticus',66,'https://upload.wikimedia.org/wikipedia/commons/2/27/Dead_sea_sparrow.jpg'),
(417,'Eurasian Tree Sparrow','Passer montanus',66,'https://upload.wikimedia.org/wikipedia/commons/9/98/Tree_Sparrow_August_2007_Osaka_Japan.jpg'),
(418,'Pale Sparrow','Carpospiza brachydactyla',66,'https://upload.wikimedia.org/wikipedia/commons/c/ce/Carpospiza_brachydactyla.jpg'),
(419,'Rock Sparrow','Petronia petronia',66,'https://upload.wikimedia.org/wikipedia/commons/d/dc/Petronia_petronia_-Ariege%2C_Midi-Pyrenee%2C_France-8-4c.jpg'),
(420,'White-winged Snowfinch','Montifringilla nivalis',66,'https://upload.wikimedia.org/wikipedia/commons/3/38/Snowfinch.jpg'),
(421,'Tree Pipit','Anthus trivialis',67,'https://upload.wikimedia.org/wikipedia/commons/6/6d/Tree_pipit_-_Jamnagar_2021-10-16.jpg'),
(422,'Red-throated Pipit','Anthus cervinus',67,'https://upload.wikimedia.org/wikipedia/commons/7/75/Red-throated_Pipit.jpg'),
(423,'Meadow Pipit','Anthus pratensis',67,'https://upload.wikimedia.org/wikipedia/commons/b/b7/Wiesenpieper_Meadow_pipit.jpg'),
(424,'Water Pipit','Anthus spinoletta',67,'https://upload.wikimedia.org/wikipedia/commons/2/24/Anthus_spinoletta_-_Water_Pipit%2C_Kahramanmara%C5%9F_2016-11-18_01-10.jpg'),
(425,'Rock Pipit','Anthus petrosus',67,'https://upload.wikimedia.org/wikipedia/commons/a/ae/2015-04-22_Anthus_petrosus%2C_Portsoy.jpg'),
(426,'Richard''s Pipit','Anthus richardi',67,'https://upload.wikimedia.org/wikipedia/commons/5/50/Anthus_richardi_-_Laem_Pak_Bia.jpg'),
(427,'Blyth''s Pipit','Anthus godlewskii',67,'https://upload.wikimedia.org/wikipedia/commons/9/94/Anthus_godlewskii_cropped.jpg'),
(428,'Tawny Pipit','Anthus campestris',67,'https://upload.wikimedia.org/wikipedia/commons/f/f4/Tawny_pipit_47.jpg'),
(429,'Western Yellow Wagtail','Motacilla flava',67,'https://upload.wikimedia.org/wikipedia/commons/5/53/2021-04-20_Motacilla_flava_flavissima%2C_Rising_Sun_CP%2C_Northumberland_1.jpg'),
(430,'Grey Wagtail','Motacilla cinerea',67,'https://upload.wikimedia.org/wikipedia/commons/3/33/Gebirgsstelze_im_Geo-Naturpark_Bergstra%C3%9Fe-Odenwald.jpg'),
(431,'Citrine Wagtail','Motacilla citreola',67,'https://upload.wikimedia.org/wikipedia/commons/e/ed/Citrine_Wagtail_%28Motacilla_citreola%29-_Breeding_Male_of_calcarata_race_at_Bharatpur_I_IMG_5752.jpg'),
(432,'White Wagtail','Motacilla alba',67,'https://upload.wikimedia.org/wikipedia/commons/4/4c/2014-04-21_Motacilla_alba_yarrellii%2C_Harthope_1.jpg'),
(433,'Common Chaffinch','Fringilla coelebs',68,'https://upload.wikimedia.org/wikipedia/commons/8/86/20240616_Buchfink_%28%28Fringilla_coelebs%29.jpg'),
(434,'Brambling','Fringilla montifringilla',68,'https://upload.wikimedia.org/wikipedia/commons/f/f7/BRAMBLING.jpg'),
(435,'Hawfinch','Coccothraustes coccothraustes',68,'https://upload.wikimedia.org/wikipedia/commons/d/dd/Coccothraustes_coccothraustes_-_01.jpg'),
(436,'Common Rosefinch','Carpodacus erythrinus',68,'https://upload.wikimedia.org/wikipedia/commons/1/19/Carpodacus_erythrinus_284921386.jpg'),
(437,'Eurasian Bullfinch','Pyrrhula pyrrhula',68,'https://upload.wikimedia.org/wikipedia/commons/8/87/Bullfinch-21-07-2008.jpg'),
(438,'Trumpeter Finch','Bucanetes githagineus',68,'https://upload.wikimedia.org/wikipedia/commons/a/a5/Trumpeter_finch_%28Bucanetes_githagineus_zedlitzi%29_male_Kebili.jpg'),
(439,'European Greenfinch','Carduelis chloris',68,'https://upload.wikimedia.org/wikipedia/commons/1/14/Carduelis_chloris_Jarom%C4%9B%C5%99_2013_3.jpg'),
(440,'Common Linnet','Carduelis cannabina',68,'https://upload.wikimedia.org/wikipedia/commons/2/29/2017.07.06.-42-Wendisch_Rietz--Bluthaenfling-Weibchen.jpg'),
(441,'Red Crossbill','Loxia curvirostra',68,'https://upload.wikimedia.org/wikipedia/commons/3/32/Loxia_curvirostra_3.png'),
(442,'European Goldfinch','Carduelis carduelis',68,'https://upload.wikimedia.org/wikipedia/commons/e/eb/072_Wild_European_goldfinch_at_the_Parc_Jura_vaudois_Photo_by_Giles_Laurent.jpg'),
(443,'European Serin','Serinus serinus',68,'https://upload.wikimedia.org/wikipedia/commons/2/2b/European_serin_%28Serinus_serinus%29_female.jpg'),
(444,'Red-fronted Serin','Serinus pusillus',68,'https://upload.wikimedia.org/wikipedia/commons/5/5f/Fire-fronted_Serin_Nainital_Uttarakhand_India_31.01.2015.jpg'),
(445,'Eurasian Siskin','Carduelis spinus',68,'https://upload.wikimedia.org/wikipedia/commons/4/4c/Carduelis_spinus_1_%28Martin_Mecnarowski%29.jpg'),
(446,'Snow Bunting','Plectrophenax nivalis',69,'https://upload.wikimedia.org/wikipedia/commons/c/c3/Plectrophenax_nivalis2.jpg'),
(447,'Black-headed Bunting','Emberiza melanocephala',70,'https://upload.wikimedia.org/wikipedia/commons/2/22/Black-headed_Bunting_Emberiza_melanocephala_Female_by_Dr._Raju_Kasambe_DSCN9313_%282%29.jpg'),
(448,'Corn Bunting','Emberiza calandra',70,'https://upload.wikimedia.org/wikipedia/commons/8/8d/Bruant_proyer_Ichkeul018.jpg'),
(449,'Rock Bunting','Emberiza cia',70,'https://upload.wikimedia.org/wikipedia/commons/d/df/Rock_Bunting_%28Cochem%29.jpg'),
(450,'Cinereous Bunting','Emberiza cineracea',70,'https://upload.wikimedia.org/wikipedia/commons/3/3d/Americantreesparrow36.jpg'),
(451,'Ortolan Bunting','Emberiza hortulana',70,'https://upload.wikimedia.org/wikipedia/commons/f/fc/Ortolan_bunting_in_Sierra_de_Guara%2C_Aragon%2C_Spain.jpg'),
(452,'Cretzschmar''s Bunting','Emberiza caesia',70,'https://upload.wikimedia.org/wikipedia/commons/b/b8/Emberiza_caesia.jpg'),
(453,'Cirl Bunting','Emberiza cirlus',70,'https://upload.wikimedia.org/wikipedia/commons/8/88/Cirl_bunting_cropped.jpg'),
(454,'Yellowhammer','Emberiza citrinella',70,'https://upload.wikimedia.org/wikipedia/commons/6/62/Goldammer_Emberiza_citrinella.jpg'),
(455,'Pine Bunting','Emberiza leucocephalos',70,'https://upload.wikimedia.org/wikipedia/commons/1/18/Emberiza_leucocephalos%3B_Baikonur-town_003.jpg'),
(456,'Reed Bunting','Emberiza schoeniclus',70,'https://upload.wikimedia.org/wikipedia/commons/a/a1/Common_reed_bunting_%28emberiza_schoeniclus%29_f.jpg'),
(457,'Yellow-breasted Bunting','Emberiza aureola',70,'https://upload.wikimedia.org/wikipedia/commons/1/10/Yellow-breasted_bunting_in_Nepal_02_-Cropped.jpg'),
(458,'Rustic Bunting','Emberiza rustica',70,'https://upload.wikimedia.org/wikipedia/commons/c/c6/Kashiradaka-01.jpg'),
(459,'Little Bunting','Emberiza pusilla',70,'https://upload.wikimedia.org/wikipedia/commons/4/4f/Little_Bunting.jpg');
ALTER TABLE birds AUTO_INCREMENT = 460;

--Categories & data according to Chandrinos G. and Kastritis Th. (2009) BIRDS at:
--Legakis, Α. & P. Maragkou (editors)
--The Red Data Book of Endangered Animals of Greece. Hellenic Zoological Society, Athens